# 服务器配置
server:
  port: 8080
  mode: debug  # debug, release, test

# 数据库配置
database:
  type: postgres  # mysql, postgres, sqlite
  host: localhost
  port: 5432
  user: root
  password: password
  dbname: go_webserver
  sslmode: disable
  timezone: Asia/Shanghai

# Redis配置
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

# 异步任务队列配置
asynq:
  concurrency: 10
  retry_count: 3
  retry_delay: 10
  redis_pool_size: 20
  queues:
    default: 5
    critical: 10
  log:
    level: info
    format: json
    output_path: ./logs/asynq.log
    max_size: 100
    max_backups: 10
    max_age: 30
    compress: true

# 日志配置
log:
  level: info  # debug, info, warn, error, dpanic, panic, fatal
  format: json  # json, console
  output_path: ./logs/app.log
  max_size: 100  # MB
  max_backups: 10
  max_age: 30  # days
  compress: true

# 国际化配置
i18n:
  default_locale: zh-CN
  bundle_path: ./i18n/locales

# HTTP客户端配置
http_client:
  timeout: 30  # 默认超时时间（秒）
  max_retries: 3  # 默认重试次数
  retry_delay: 1  # 重试延迟（秒）
  enable_request_log: true  # 是否启用请求日志
  enable_response_log: true  # 是否启用响应日志
  headers:  # 默认请求头
    User-Agent: "review-manager/1.0"
    Accept: "application/json"
  proxy_url: ""  # 代理URL，为空则不使用代理
  insecure_skip_verify: false  # 是否跳过TLS证书验证
  services:  # 依赖服务配置
    taskManager:  # 任务管理服务
      base_url: "http://task-manager"
      timeout: 10  # 覆盖默认超时时间
      max_retries: 2  # 覆盖默认重试次数
    issueManager:  # 任务管理服务
      base_url: "http://issue-manager"
      timeout: 10  # 覆盖默认超时时间
      max_retries: 2  # 覆盖默认重试次数
    kbCenter:   # 上下文服务
      base_url: "http://kb-center"
      timeout: 10  # 覆盖默认超时时间
      max_retries: 2  # 覆盖默认重试次数
